### ISSUE TITLE
coffeescript version out-of-date

### ISSUE THREAD

**Issue by crazymykl** [codeclimate/codeclimate-coffeelint#26]
Version 1.16.0 of `coffeelint` allows use of `import` and `export` keywords without backticks in coffeescript.

**Comment by gdiggs** [comment]
@crazymykl thanks for opening this! I'm not sure when we will be able to address this, but I've added the help wanted tag. If you open a PR, I would be happy to merge it!

One thing to look out for: are there any breaking changes between the version we are running and 1.16.0?

**Comment by crazymykl** [comment]
Actually, it looks like it's the version of coffeescript itself, and not coffeelint, that is out of date. I pulled down all the stuff necessary to start on a PR, but the issue didn't appear locally. Are y'all running a coffeescript pre-1.11?

**Comment by dblandin** [comment]
@crazymykl Looks like we're currently using coffeescript v1.10.0

https://github.com/codeclimate/codeclimate-coffeelint/blob/master/npm-shrinkwrap.json#L20-L24

You can test your local changes by rebuilding the docker image and running the engine from the CLI:

```shell
# in codeclimate/codeclimate-coffeelint directory
$ make image
# in a coffeescript project directory
$ codeclimate analyze -e coffeelint
```

**Comment by crazymykl** [comment]
Right, the issue is actually that `import` and `export` were syntax errors until 1.11.

**Comment by chrishulton** [comment]
Fixed in https://github.com/codeclimate/codeclimate-coffeelint/pull/28
